# Generated by Django 5.2.6 on 2025-09-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100, null=True)),
                ("tracking_number", models.CharField(max_length=50, unique=True)),
                ("purchase_order", models.CharField(max_length=50, unique=True)),
                ("waybill_number", models.CharField(max_length=50, unique=True)),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "last_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("status_description", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField()),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="freight.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
